'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace TCKimlikWebServiceReference
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://tckimlik.nvi.gov.tr/WS", ConfigurationName:="TCKimlikWebServiceReference.KPSPublicSoap")>  _
    Public Interface KPSPublicSoap
        
        'CODEGEN: Generating message contract since element name Ad from namespace http://tckimlik.nvi.gov.tr/WS is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tckimlik.nvi.gov.tr/WS/TCKimlikNoDogrula", ReplyAction:="*")>  _
        Function TCKimlikNoDogrula(ByVal request As TCKimlikWebServiceReference.TCKimlikNoDogrulaRequest) As TCKimlikWebServiceReference.TCKimlikNoDogrulaResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tckimlik.nvi.gov.tr/WS/TCKimlikNoDogrula", ReplyAction:="*")>  _
        Function TCKimlikNoDogrulaAsync(ByVal request As TCKimlikWebServiceReference.TCKimlikNoDogrulaRequest) As System.Threading.Tasks.Task(Of TCKimlikWebServiceReference.TCKimlikNoDogrulaResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class TCKimlikNoDogrulaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="TCKimlikNoDogrula", [Namespace]:="http://tckimlik.nvi.gov.tr/WS", Order:=0)>  _
        Public Body As TCKimlikWebServiceReference.TCKimlikNoDogrulaRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As TCKimlikWebServiceReference.TCKimlikNoDogrulaRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tckimlik.nvi.gov.tr/WS")>  _
    Partial Public Class TCKimlikNoDogrulaRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public TCKimlikNo As Long
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Ad As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Soyad As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=3)>  _
        Public DogumYili As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal TCKimlikNo As Long, ByVal Ad As String, ByVal Soyad As String, ByVal DogumYili As Integer)
            MyBase.New
            Me.TCKimlikNo = TCKimlikNo
            Me.Ad = Ad
            Me.Soyad = Soyad
            Me.DogumYili = DogumYili
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class TCKimlikNoDogrulaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="TCKimlikNoDogrulaResponse", [Namespace]:="http://tckimlik.nvi.gov.tr/WS", Order:=0)>  _
        Public Body As TCKimlikWebServiceReference.TCKimlikNoDogrulaResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As TCKimlikWebServiceReference.TCKimlikNoDogrulaResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tckimlik.nvi.gov.tr/WS")>  _
    Partial Public Class TCKimlikNoDogrulaResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public TCKimlikNoDogrulaResult As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal TCKimlikNoDogrulaResult As Boolean)
            MyBase.New
            Me.TCKimlikNoDogrulaResult = TCKimlikNoDogrulaResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface KPSPublicSoapChannel
        Inherits TCKimlikWebServiceReference.KPSPublicSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class KPSPublicSoapClient
        Inherits System.ServiceModel.ClientBase(Of TCKimlikWebServiceReference.KPSPublicSoap)
        Implements TCKimlikWebServiceReference.KPSPublicSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function TCKimlikWebServiceReference_KPSPublicSoap_TCKimlikNoDogrula(ByVal request As TCKimlikWebServiceReference.TCKimlikNoDogrulaRequest) As TCKimlikWebServiceReference.TCKimlikNoDogrulaResponse Implements TCKimlikWebServiceReference.KPSPublicSoap.TCKimlikNoDogrula
            Return MyBase.Channel.TCKimlikNoDogrula(request)
        End Function
        
        Public Function TCKimlikNoDogrula(ByVal TCKimlikNo As Long, ByVal Ad As String, ByVal Soyad As String, ByVal DogumYili As Integer) As Boolean
            Dim inValue As TCKimlikWebServiceReference.TCKimlikNoDogrulaRequest = New TCKimlikWebServiceReference.TCKimlikNoDogrulaRequest()
            inValue.Body = New TCKimlikWebServiceReference.TCKimlikNoDogrulaRequestBody()
            inValue.Body.TCKimlikNo = TCKimlikNo
            inValue.Body.Ad = Ad
            inValue.Body.Soyad = Soyad
            inValue.Body.DogumYili = DogumYili
            Dim retVal As TCKimlikWebServiceReference.TCKimlikNoDogrulaResponse = CType(Me,TCKimlikWebServiceReference.KPSPublicSoap).TCKimlikNoDogrula(inValue)
            Return retVal.Body.TCKimlikNoDogrulaResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function TCKimlikWebServiceReference_KPSPublicSoap_TCKimlikNoDogrulaAsync(ByVal request As TCKimlikWebServiceReference.TCKimlikNoDogrulaRequest) As System.Threading.Tasks.Task(Of TCKimlikWebServiceReference.TCKimlikNoDogrulaResponse) Implements TCKimlikWebServiceReference.KPSPublicSoap.TCKimlikNoDogrulaAsync
            Return MyBase.Channel.TCKimlikNoDogrulaAsync(request)
        End Function
        
        Public Function TCKimlikNoDogrulaAsync(ByVal TCKimlikNo As Long, ByVal Ad As String, ByVal Soyad As String, ByVal DogumYili As Integer) As System.Threading.Tasks.Task(Of TCKimlikWebServiceReference.TCKimlikNoDogrulaResponse)
            Dim inValue As TCKimlikWebServiceReference.TCKimlikNoDogrulaRequest = New TCKimlikWebServiceReference.TCKimlikNoDogrulaRequest()
            inValue.Body = New TCKimlikWebServiceReference.TCKimlikNoDogrulaRequestBody()
            inValue.Body.TCKimlikNo = TCKimlikNo
            inValue.Body.Ad = Ad
            inValue.Body.Soyad = Soyad
            inValue.Body.DogumYili = DogumYili
            Return CType(Me,TCKimlikWebServiceReference.KPSPublicSoap).TCKimlikNoDogrulaAsync(inValue)
        End Function
    End Class
End Namespace
